### ISSUE TITLE
I tried this model with CUB200 dataset and only get about 25% test accuracy?

### ISSUE THREAD

**Issue by iamzifei** [iversonicter/Learn-to-pay-attention#1]
Have you tried the CUB200 dataset as the paper also test it? I'm not sure what I did wrong and would like to see a CUB200 example included.

**Comment by wangyongjie-ntu** [comment]
Sorry, I have not tried CUB200 datasets. 
I created the project just to see whether the attention can improve the performance on the food recognition task(classification). 
It has some improvement on the CIFAR100, no clear improvement on the Food101 dataset even with some simple tuning. Actually, I do not understand why. 

The previous food project has been done. And I switch to another project about explainable AI, no longer dig into this topic. 

You can leave a message in the original[ repo](https://github.com/SaoYan/LearnToPayAttention/issues) or send an email to the author.

Hope this can help you.
