### ISSUE TITLE
Why the conv_block2 has 3 layers?

### ISSUE THREAD

**Issue by Chauncey-Wang** [iversonicter/Learn-to-pay-attention#2]
The vgg-19 has two 3x3 Conv,128 in conv_block2 ，but why your net has 3 layers in conv_block2？
The code is on the 27th line of vgg19.py

`self.conv_block2 = self._conv_block(64, 128, 3)`

**Comment by wangyongjie-ntu** [comment]
Thanks. You are correct. 
There is a mistake here. You can replace "3" with "2",  and train the network on CIFAR10/100 dataset. 
If any difference with the results reported here, please kindly let me know.
